language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
before_install:
  - python --version
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install -U pluggy; fi
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -e .
  - pip install pytest-cov codecov
script:
  - pytest tests --cov=. tests
after_success:
  - codecov